services:
  
  iqsignv1_db:
    environment:
      POSTGRES_USER: spr
      POSTGRES_PASSWORD: testing123
    image: postgres:12
    ports:
      - 5432:5432
    restart: always
  
  iqsignv1:
    environment:
      POSTGRES_USER: spr
      POSTGRES_PASSWORD: testing123
    build:
      context: .
      dockerfile: iqsign.Dockerfile
    ports:
      - 3333:3333
      - 3335:3335
      - 3336:3336
    working_dir: /app/iqsign/
    command: /app/iqsign/startd.sh

  iqsignv2:
    build:
      context: .
      dockerfile: iqsign-v2.Dockerfile
    ports:
      - 5172:5172
      - 3010:3010
    environment:
      NODE_ENV: development
    working_dir: /app/iqsignv2
    command: npm run dev -- --host 0.0.0.0
