name: Test ALDS
on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Dart environment
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          working-directory: ./flutter/alds/test

      # Step 3: Run Dart commands
      - name: Run Dart tests
        run: |
          dart pub get
          dart format --output=none --set-exit-if-changed
          dart analyze
          dart test
          dart map_page_test.dart
          dart nav_bar_test.dart
          dart saved_locations_test.dart
          dart settings_test.dart
          dart storage_test.dar
