name: iQsign 2.0 Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          working-directory: iqsignv2

  dart-tests:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2 # 使用 Flutter Action

      # Step 3: Run Flutter commands
      - name: Run Flutter Tests
        working-directory: ./flutter/alds/test
        run: |
          flutter pub get
          flutter format . --dry-run --set-exit-if-changed
          flutter analyze
          flutter test
